repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.97.4
  hooks:
    - id: terraform_fmt
    - id: terraform_tflint
      args:
        - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
    - id: terraform_docs
      args:
        - --hook-config=--add-to-existing-file=true
        - --hook-config=--create-file-if-not-exist=true

